import { pascalCase } from "es-toolkit";
import type { CustomElementEntry, RuntimeOnlyEntry, SSREntry } from "../plugin";

export function safeComponentName(name: string, index: number) {
  const pc = pascalCase(name);
  if (/^[A-Z][A-Za-z0-9]*$/.test(pc)) {
    return pc;
  }
  console.warn(
    `[hyacine] Warning: Unsafe component name "${name}" converted to safe default "HyacineComponent${index}".`,
  );
  return `HyacineComponent${index}`;
}

function safeImportPath(path: string): string {
  // 使用 JSON 字符串字面量来避免引号/换行等导致的代码注入
  // 例：import X from "...";
  return JSON.stringify(path);
}

function safeHydrationInstruction(
  hydration: SSREntry["clientHydrationInstruction"],
): SSREntry["clientHydrationInstruction"] | undefined {
  // manifest 来自外部数据时，类型约束并不等于运行时安全；这里做白名单校验。
  if (
    hydration === "load" ||
    hydration === "idle" ||
    hydration === "visible" ||
    hydration === "media"
  ) {
    return hydration;
  }
  console.warn(
    `[hyacine] Warning: Invalid client hydration instruction "${hydration}" detected. Ignoring it for safety.`,
  );
  return undefined;
}

/**
 * 将 props 对象序列化为 Astro 组件属性字符串
 * 例如: { title: "Hello", count: 42 } => ' title="Hello" count={42}'
 */
function serializeProps(props: Record<string, unknown>): string {
  const entries = Object.entries(props);
  if (entries.length === 0) return "";

  return entries
    .map(([key, value]) => {
      // 校验 key 是否是安全的属性名
      if (!/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) {
        console.warn(`[hyacine] Warning: Invalid prop name "${key}" detected. Skipping this prop.`);
        return "";
      }

      // 根据值的类型决定如何序列化
      if (typeof value === "string") {
        // 字符串值用双引号包裹，需要转义内部的引号和反斜杠
        const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        return ` ${key}="${escaped}"`;
      } else if (typeof value === "number" || typeof value === "boolean") {
        // 数字和布尔值使用 JSX 表达式语法
        return ` ${key}={${value}}`;
      } else if (value === null || value === undefined) {
        // null 和 undefined 跳过
        return "";
      } else {
        // 对象、数组等复杂类型使用 JSON 序列化后作为 JSX 表达式
        try {
          const serialized = JSON.stringify(value);
          return ` ${key}={${serialized}}`;
        } catch (error) {
          const errorMessage = error instanceof Error ? error.message : String(error);
          console.warn(
            `[hyacine] Warning: Failed to serialize prop "${key}": ${errorMessage}. Skipping this prop.`,
          );
          return "";
        }
      }
    })
    .filter((s) => s !== "")
    .join("");
}

export function generateTempAstroTemplateFile(entries: (SSREntry | CustomElementEntry)[]): string {
  let importsArea = "";

  let usageArea = "";

  const seenPaths = new Set<string>();

  entries.forEach((entry, index) => {
    if (seenPaths.has(entry.path)) {
      console.warn(
        `[hyacine] Warning: Duplicate entry path "${entry.path}" detected. Skipping duplicate import.`,
      );
      return;
    }
    seenPaths.add(entry.path);

    const componentName = safeComponentName(entry.name, index);
    importsArea += `import ${componentName} from ${safeImportPath(entry.path)};\n`;

    if (entry.type === "custom-element") {
      usageArea += `<${componentName} style="display: none;" />\n`;
    } else if (entry.type === "ssr") {
      const hydration = safeHydrationInstruction(entry.clientHydrationInstruction);
      const hydrationAttr = hydration ? ` client:${hydration}` : "";
      const propsAttr = entry.props ? serializeProps(entry.props) : "";
      usageArea += `<${componentName}${hydrationAttr}${propsAttr} />\n`;
    }
  });

  return `
  ---
  //⚠️ This file is auto-generated by hyacine plugin system. Do not edit directly!
  // @ts-nocheck
  ${importsArea}
  ---
  <Fragment>
    ${usageArea}
  </Fragment>
  `.trim();
}

export function generateTempRuntimeFile(
  entries: RuntimeOnlyEntry[],
  injectPoints: Record<string, string>,
): string {
  let importsArea = "";
  let initArea = "";

  const seenPaths = new Set<string>();

  entries.forEach((entry, index) => {
    if (seenPaths.has(entry.path)) return;
    seenPaths.add(entry.path);

    const componentName = safeComponentName(entry.name, index);
    const initAlias = `init_${componentName}`;
    importsArea += `import { init as ${initAlias} } from ${safeImportPath(entry.path)};\n`;
    initArea += `${initAlias}();\n`;
  });

  // 序列化 injectPoints 为 JavaScript 对象
  const injectPointsJSON = JSON.stringify(injectPoints, null, 2);

  return `
  //⚠️ This file is auto-generated by hyacine plugin system. Do not edit directly!
  // @ts-nocheck
  
  /**
   * 全局注入点选择器映射表
   * @internal
   */
  const HYACINE_INJECT_POINTS = ${injectPointsJSON};

  /**
   * 获取指定注入点的 CSS 选择器
   * @param injectPoint - 注入点名称
   * @returns CSS 选择器字符串，如果不存在则返回 undefined
   * @example
   * const selector = getInjectPointSelector('comment');
   * const element = document.querySelector(selector);
   */
  export function getInjectPointSelector(injectPoint: string): string | undefined {
    return HYACINE_INJECT_POINTS[injectPoint];
  }
  
  ${importsArea}

  ${initArea}
  `.trim();
}
